name: Sync Upstream

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *" # Execute every hour

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Job-level permissions configuration starts here
      contents: write # 'write' access to repository contents
      pull-requests: write # 'write' access to pull requests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Use the GitHub checkout action to checkout code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # Specify Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node scripts/sync-upstream.js # Execute your Node.js script

      - name: Commit changes
        run: |
          git config --global user.email "github@suiet.app"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-update from script" || echo "No changes to commit"
          git push
